In [2]:
import numpy as np
print(np.version)
print(np.show_config ())

<module 'numpy.version' from 'C:\\Users\\Tanuja Chintada\\Downloads\\New folder\\lib\\site-packages\\numpy\\version.py'>
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Tanuja Chintada/Downloads/New folder\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Tanuja Chintada/Downloads/New folder\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Tanuja Chintada/Downloads/New folder\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Tanuja Chintada/Downloads/New folder\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Tanuja Chintada/Downloads/New folder\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Tanuja Chintada/Downloads/New folder\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']

In [4]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [5]:
import numpy as np
x=np.array([1,2,3,4])
print(x)
print(np.all(x))
y=np.array([0,1,2,3,4])
print(y)
print(np.all(y))

[1 2 3 4]
True
[0 1 2 3 4]
False


In [6]:
x.any()
y.any()

True

In [8]:
x=[0,0,0,0]
print(np.any(x))

False


In [10]:
y=[1,2,0,0]
print(np.any(y))

True


In [13]:
a=np.array([1,0,np.nan,np.inf])
print(a)
print(np.isfinite(a))

[ 1.  0. nan inf]
[ True  True False False]


In [14]:
x=np.array([12.5,66,9,0,np.nan])
print(np.isfinite(x))

[ True  True  True  True False]


In [16]:
x=np.array([15,23.5,np.nan,np.inf,1,0])
print(x)
print(np.isinf(x))

[15.  23.5  nan  inf  1.   0. ]
[False False False  True False False]


In [19]:
y=np.array([np.nan,np.inf])
print(np.isinf(y))
print(np.isposinf(y))
print(np.isneginf(y))

[False  True]
[False  True]
[False False]


In [20]:
x=np.array([np.nan,np.inf,-98,9,1])
print(x)
print(np.isnan(x))

[ nan  inf -98.   9.   1.]
[ True False False False False]


In [23]:
import numpy as np 
a=np.array([1+2j,2.5,np.nan,np.inf,1,0+1j])
print(np.isscalar(a))
print(np.iscomplex(a))
print(np.isreal(a))

False
[ True False False False False  True]
[False  True  True  True  True False]


In [24]:
np.isscalar(1)

True

In [25]:
np.isscalar(2.7)

True

In [26]:
np.isscalar(1+2j)

True

In [27]:
np.isscalar(np.nan)

True

In [28]:
np.isscalar(np.inf)

True

In [3]:
import numpy as np
rand_num=np.random.normal(0,1,1)
print(rand_num)

[-0.32744897]


In [8]:
import numpy as np
x=np.linspace(0,10,5)
print(x)

[ 0.   2.5  5.   7.5 10. ]


In [13]:
import numpy as np 
x=np.arange(21)
print(x)
print[(x>=9)&(x<=15)]*=-1
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


TypeError: 'builtin_function_or_method' object is not subscriptable

In [2]:
import numpy as np
arr1=np.zeros(10)
print(arr1)
arr2=np.ones(10)
print(arr2)
arr3=np.ones(10)*10
print(arr3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


In [3]:
import  numpy as np
arr=np.arange(30,71)
print(arr)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [4]:
import numpy as np
arr=np.arange(0,101)
print(arr)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [5]:
import numpy as np              //print even integers from 30 to 70
arr=np.arange(30,71,2)
print(arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [6]:
import numpy as np
arr=np.identity(3)
print("3*3 matrix")
print(arr)

3*3 matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
import numpy as np
arr=np.identity(5)
print("5*5 matrix")
print(arr)

5*5 matrix
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
import numpy as np
arr=np.random.normal(0,1,2)
print("random numbers between 0 and 1")
print(arr)

[-0.57609503  0.37800692]


In [15]:
import numpy as np
arr=np.random.normal(0,1,15)
print("random numbers between 0 and 5")
print(arr)

random numbers between 0 and 5
[-1.92932743  0.00392463  1.14579881  0.20229232 -0.49837863 -0.54361087
 -0.9799938   0.50900737  0.43330263 -0.19318871  2.19662409 -1.74578896
 -0.48079384  0.73737559  0.31213999]


In [16]:
import numpy as np
arr=np.arange(10,31)
print(arr)
print(arr[1:-1])
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [19]:
import numpy as np
arr=np.arange(15,55)
print(arr)
print(arr[5:-5])


[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]


In [20]:
import numpy as np
arr=np.arange(12,24).reshape((3,4))
print(arr)


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [22]:
import numpy as np
arr=np.linspace(10,49,5)
print(arr)
arr=np.linspace(0,10,5)
print(arr)


[10.   19.75 29.5  39.25 49.  ]
[ 0.   2.5  5.   7.5 10. ]


In [25]:
import numpy as np
arr=np.arange(21)
print(arr)
arr[(arr>=9)&(arr<=15)]*=-1
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [26]:
import numpy as np
arr=np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [28]:
import numpy as np
arr=np.ones((10,10))
arr[1:-1]=0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [31]:
import numpy as np
arr=np.ones((10,10))
arr[1:-1, 1:-1]=3
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 3. 3. 3. 3. 3. 3. 3. 3. 1.]
 [1. 3. 3. 3. 3. 3. 3. 3. 3. 1.]
 [1. 3. 3. 3. 3. 3. 3. 3. 3. 1.]
 [1. 3. 3. 3. 3. 3. 3. 3. 3. 1.]
 [1. 3. 3. 3. 3. 3. 3. 3. 3. 1.]
 [1. 3. 3. 3. 3. 3. 3. 3. 3. 1.]
 [1. 3. 3. 3. 3. 3. 3. 3. 3. 1.]
 [1. 3. 3. 3. 3. 3. 3. 3. 3. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [2]:
import numpy as np
arr=np.arange(10,22).reshape((3,4))
print(arr)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [4]:
import numpy as np
arr=np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [5]:
import numpy as np
arr=np.diag([1,2,3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [15]:
import numpy as np
x=np.random.random((4,3,3))
print(x)

[[[0.45826865 0.09755854 0.55157473]
  [0.0669997  0.49668916 0.60088539]
  [0.02667442 0.61847825 0.91316114]]

 [[0.78002811 0.87961548 0.26069728]
  [0.05114396 0.17337341 0.15363419]
  [0.86026139 0.4535794  0.08150627]]

 [[0.074406   0.19990771 0.35146386]
  [0.38967394 0.35582426 0.91637359]
  [0.83862771 0.11115904 0.70152283]]

 [[0.22995464 0.79117816 0.72618708]
  [0.53327878 0.68380212 0.18492264]
  [0.47147302 0.59780544 0.04952979]]]


In [23]:
import numpy as np
x=np.array([[1,2],[3,4]])
print(x)
y=np.sum(x)
print(y)
print(np.sum(x,axis=0))  //sum of columns
print(np.sum(x,axis=1))   //sum of rows


[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [25]:
import numpy as np 
x=np.array([2,4])
y=np.array([7,3])
print("original array")
print(x)
print(y)
print("inner product of two matrices")
print(np.dot(x,y))


original array
[2 4]
[7 3]
inner product of two matrices
26
